version: 2.1

# run job
jobs:
  build:
    # home dir
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    # step
    setps:
      - checkout
      - run: python3 main.py
    test:
      working_directory: ~/circleci-python
      docker:
        - image: "circleci/python:3.6.4"
      steps:
        - checkout
        - run: python3 main-test.py

  workflows:
    build_and_test:
      jobs:
        # build job 실행
        - build
        # test job 실행
        - test:
          # build가 성공하지 않았으면 test 실행하지 않음
          requires:
            - build
