version: 2.1

# job description
jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main-test.py

# 실제 workflow(job들의 실행)
workflows:
  build_and_test:
    # 해야할 업무
    jobs:
      - build
      - test:
          # test 전에 필수적으로 해야할 job
          requires:
            - build
